spring:
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: user
        password: 123
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    h2: 
        console:
            enabled: true

api-param:
    url: https://api.stackexchange.com/2.3/search/advanced
    siteParam: stackoverflow-erro